insert into orgao (descricao) VALUES ('SECRETARIA DE FINANÇAS'), ('SECRETARIA DE CONSERVAÇÃO E SERVIÇOS PÚBLICOS'),
('SECRETARIA DE PLANEJAMENTO, ORÇAMENTO E GESTÃO'), ('INSTITUTO JOSÉ FROTA'), ('SECRETARIA EXECUTIVA REGIONAL I'),
('SECRETARIA EXECUTIVA REGIONAL II'), ('SECRETARIA EXECUTIVA REGIONAL III'), ('SECRETARIA DE EDUCAÇÃO'),
('SECRETARIA DE SAÚDE'),('HOSPITAL DA MULHER');
insert into setor (descricao) VALUES ('FINANCEIRO'), ('COMERCIAL'), ('MARKETING'), ('OPERACIONAL'), ('RECURSOS HUMANOS'),
('DIRETORIA'), ('ACESSORIA DE IMPRENSA');